### ISSUE TITLE
miniconda3 version

### ISSUE THREAD

**Issue by serge2016** [griffithlab/docker-pvactools#12]
Hello!
Why do you use the version `continuumio/miniconda3:4.5.4` to start docker image from? I didn't find it in the builds, but later I found it in tags: https://hub.docker.com/r/continuumio/miniconda3/tags. Maybe it's time to switch to 4.5.12?

**Comment by susannasiebert** [comment]
That was the version that was available when we first started making these docker images and we haven't had any problems with it so we haven't seen a need to update to a later version. Is there a specific reason you would like a newer miniconda version in our image?

**Comment by serge2016** [comment]
@susannasiebert No, it's just a question, sorry. At first, I didn't find this version (4.5.4) in builds, that's why I started to inspect.

**Comment by susannasiebert** [comment]
It's not a bad idea to update. It's just not very high on our list of priorities. I will leave this issue open so that I remember to update it when I get a chance.

**Comment by Stikus** [comment]
Looks like you are not using `miniconda3` as starting image now - time to close?

**Comment by susannasiebert** [comment]
Good catch. Thank you. Closing.
