### ISSUE TITLE
Is particular mhcflurry version specified?

### ISSUE THREAD

**Issue by serge2016** [griffithlab/docker-pvactools#13]
Hello!
I'm not sure right now, but are the versions of MHC prediction tools somehow frozen in this installation?
For example, mhcflurry is installed, but is it's version specified anywhere inside pvactools requirements?
https://github.com/griffithlab/docker-pvactools/blob/f2134e6b24f1023c049ad2fd948ecd1c4e5cea91/Dockerfile#L52

**Comment by susannasiebert** [comment]
MHCflurry and MHCnuggets are not pinned to a specific version. Thus, in our Docker containers they are whatever version was the latest when the container was created. You can determine what version of a pip package is installed by doing the following:
```
$ docker run -it griffithlab/pvactools:1.3.5
(base) root@1370385d46ba:/opt/iedb# pip show mhcflurry
Name: mhcflurry
Version: 1.2.3
Summary: MHC Binding Predictor
Home-page: https://github.com/hammerlab/mhcflurry
Author: Tim O'Donnell and Alex Rubinsteyn
Author-email: timodonnell@gmail.com
License: http://www.apache.org/licenses/LICENSE-2.0.html
Location: /opt/conda/lib/python3.6/site-packages
Requires: pyyaml, mhcnames, Keras, tqdm, numpy, tensorflow, scikit-learn, pandas, appdirs, six
Required-by: pvactools
```
So in the 1.3.5 container MHCflurry is version 1.2.3

**Comment by Stikus** [comment]
@susannasiebert Hello, another question about MHCflurry version:
Now we installing 1.4.3 version of MHCflurry:
```
Collecting mhcflurry
  Downloading https://files.pythonhosted.org/packages/3f/f3/7e903252c6e752d80ffc56a4596429fd2f202a7dd3586fb78c6fe85c6ef4/mhcflurry-1.4.3-py3-none-any.whl (96kB)
```
Do we still need to pin version [here](https://github.com/griffithlab/docker-pvactools/blob/f4e351ca8d7ffb3abd00b3d9609041015f001e96/Dockerfile#L52):
`ENV MHCFLURRY_DOWNLOADS_CURRENT_RELEASE=1.2.0`
or should we upgrade it?

**Comment by susannasiebert** [comment]
I apologize for the oversight; I should've upgrade this env variable to match the latest MHCflurry version. It should still work but the data that their model is based on will be old. I plan on fixing that in any docker images going forward.

**Comment by Stikus** [comment]
Hello again, @susannasiebert  :)
Same question:
```
Collecting mhcflurry
  Downloading mhcflurry-1.6.0-py3-none-any.whl (133 kB)
```
While:
`ENV MHCFLURRY_DOWNLOADS_CURRENT_RELEASE=1.4.0`

Upgrade?
