### ISSUE TITLE
pvactools docker postgresql to fix Viz issue

### ISSUE THREAD

**Issue by EdGreen21** [griffithlab/docker-pvactools#19]
pvactools-viz doesn't run correctly as postgresql isn't correctly installed (see main pvactools issue https://github.com/griffithlab/pVACtools/issues/250).

There are several examples of Docker based postgresql installs on Ubuntu based systems:
https://github.com/rgielen/postgresql-ubuntu-docker/blob/master/Dockerfile
https://hub.docker.com/r/partlab/ubuntu-postgresql/dockerfile

We hope to shortly be making some commit suggestions as to how to incorporate this into the main pvactools Docker image

**Comment by susannasiebert** [comment]
3.0 has removed pVACviz and replaced with our new visualization tool pVACview.
