### ISSUE TITLE
Build docker image on Ubuntu to match VEP dockerfile

### ISSUE THREAD

**Issue by EdGreen21** [griffithlab/docker-pvactools#7]
**Development Suggestion**
Base container on Ubuntu 16:04 instead of miniconda

**Benefits**
1 - The `ENSEMBL VEP` dockerfile [link](https://hub.docker.com/r/ensemblorg/ensembl-vep/dockerfile) is based on `Ubuntu16.04`, allowing a multi-stage docker build to make a container that can process `*.vcf` files as well as later `pVACtools `steps.

2 - pvactools can be installed using `pip`; `Ubuntu16.04` ships with `Python 3.5`, so potentially avoid need for need for `conda` environments.

3 - ability to combine with other Ubuntu based builds such as [this one](https://hub.docker.com/r/danielguerra/ubuntu-xrdp) allowing full XRDP support, making the pvacviz GUI easily accessible. Alternative would be to alter the pvacviz code (as suggested in pvactools issue #257 [here](https://github.com/griffithlab/pVACtools/issues/257)) to potentially host to access `pvacviz `browser using port forwarding.

**Potential Costs**
If there are remaining conda dependencies in pvactools this would require the installation of miniconda in the docker file, following the guidelines in the miniconda dockerfile [here](https://hub.docker.com/r/continuumio/miniconda3/dockerfile) but adding maintenance overhead

**Comment by susannasiebert** [comment]
conda is required in this image for IEDB since it runs on python2.7. A docker container for VEP with the plugins needed for pVACseq is available here: https://hub.docker.com/r/mgibio/vep/

**Comment by EdGreen21** [comment]
Thanks Susanna, that also had the 

`RUN wget https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/90/Downstream.pm`

line that I was looking for
